### ISSUE TITLE
fileNamePattern fails on files such as thing.test.js

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify-plugin#38]
Started integrating this into fastify toString and recognized the regex pattern fails on composite files (such as `toString.test.js`). Working on a fix right now!

**Comment by fox1t** [comment]
There is also a problem with fpStackTracePattern. I updated fastify-plugin to the last version and now it fails on `m[1].match(fileNamePattern)[1]` because m is null. This is the full stack trace:
```
TypeError: Cannot read property '1' of null
    at checkName (/Users/maksim/Projects/evologi/evo-shipping/node_modules/fastify-plugin/index.js:48:10)
    at Object.plugin [as default] (/Users/maksim/Projects/evologi/evo-shipping/node_modules/fastify-plugin/index.js:15:29)
    at Object.<anonymous> (/Users/maksim/Projects/evologi/evo-shipping/src/lib/authentication/index.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module.m._compile (/Users/maksim/Projects/evologi/evo-shipping/node_modules/ts-node/src/index.ts:430:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/maksim/Projects/evologi/evo-shipping/node_modules/ts-node/src/index.ts:433:12)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/maksim/Projects/evologi/evo-shipping/src/routes/api/v1.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module.m._compile (/Users/maksim/Projects/evologi/evo-shipping/node_modules/ts-node/src/index.ts:430:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
```
As you can see i use typescript with ts-node for the dev setup. There are two different problems here:
1. `fpStackTracePattern` pattern serches just for `plugin` word, in my case it is needed something as `const fpStackTracePattern = new RegExp('at\\s{1}Object.plugin\\s{1}.*\\n\\s*(.*)')`. 
2. `fileNamePattern` has .js extension hardcoded and in my case it is .ts. If i adjust it as `const fileNamePattern = new RegExp('(?:\\/|\\\\)(\\w*(\\.\\w*)*)\\.ts')` it works like e charm.

I think that here we have to options:
1. Adjust regexp to include as many cases as it can, also for .ts development
2. If `m` is null just fail in silence.

If needed i can make a patch and a PR.

**Comment by fox1t** [comment]
Ok, working on it

**Comment by fox1t** [comment]
check it here and let me know https://github.com/fastify/fastify-plugin/pull/41

**Comment by StarpTech** [comment]
I also have to implement that approach in my hemera framework. I goes with this:

```js
    const calleeFile = getCallerFile()
    if (calleeFile) {
      const basename = path.basename(calleeFile)
      if (basename.toLowerCase().indexOf('plugin') !== -1) {
        fn[DISPLAY_NAME_SYMBOL] = basename
          .replace(/([-_.]*)?plugin([-_]*)?/gi, '')
          .replace(/\.js|\.ts$/i, '')
      }
    }

// https://stackoverflow.com/a/29581862/1893773
function getCallerFile() {
  var originalFunc = Error.prepareStackTrace

  var callerfile
  try {
    var err = new Error()
    var currentfile

    Error.prepareStackTrace = function(_, stack) {
      return stack
    }

    currentfile = err.stack.shift().getFileName()

    while (err.stack.length) {
      callerfile = err.stack.shift().getFileName()

      if (currentfile !== callerfile) break
    }
  } catch (e) {}

  Error.prepareStackTrace = originalFunc

  return callerfile
}
```

**Comment by mcollina** [comment]
I think this specifically has been solved. If you can improve the code @StarpTech, feel free to send a PR!
